name: Luakit tests

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install depenencies
      run: |
        sudo apt-get update
        sudo apt-get install luajit libluajit-5.1-dev libjavascriptcoregtk-4.0-dev libwebkit2gtk-4.1-dev libgtk-3-dev libglib2.0-dev luarocks
    - name: Install lua dependencies
      run: |
        sudo luarocks --lua-version 5.1 install luafilesystem
        sudo luarocks --lua-version 5.1 install luassert
        sudo luarocks --lua-version 5.1 install luacheck
    - name: make
      run: make
    - name: make run-tests
      run: make run-tests
